"""
Makerspace RAG - Main Launcher
One-click launcher that sets up everything and starts the application
"""

import os
import sys
import time
import json
import webbrowser
import threading
import subprocess
from pathlib import Path

# Add parent directory to path for imports
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

ENV_FILE = PROJECT_ROOT / '.env'
FIRST_RUN_MARKER = PROJECT_ROOT / '.initialized'


def print_banner():
    """Print application banner."""
    print("\n" + "="*60)
    print("""
    __  __       _
   |  \/  | __ _| | _____ _ __ ___ _ __   __ _  ___ ___
   | |\/| |/ _` | |/ / _ \ '__/ __| '_ \ / _` |/ __/ _ \\
   | |  | | (_| |   <  __/ |  \__ \ |_) | (_| | (_|  __/
   |_|  |_|\__,_|_|\_\___|_|  |___/ .__/ \__,_|\___\___|
                                  |_|    RAG Assistant
    """)
    print("="*60)


def print_status(message, status="INFO"):
    """Print formatted status message."""
    icons = {"INFO": "i", "OK": "+", "WARN": "!", "ERROR": "x", "WAIT": "~"}
    icon = icons.get(status, "*")
    print(f"  [{icon}] {message}")


def is_first_run():
    """Check if this is the first run."""
    return not FIRST_RUN_MARKER.exists()


def mark_initialized():
    """Mark that first-run setup is complete."""
    with open(FIRST_RUN_MARKER, 'w') as f:
        f.write(f"Initialized: {time.strftime('%Y-%m-%d %H:%M:%S')}")


def check_python_dependencies():
    """Check if required Python packages are installed."""
    required = ['flask', 'flask_cors', 'flask_login', 'sqlalchemy', 'sklearn', 'numpy', 'requests', 'pymysql']
    missing = []

    for package in required:
        try:
            __import__(package.replace('-', '_'))
        except ImportError:
            missing.append(package)

    if missing:
        print_status(f"Missing packages: {', '.join(missing)}", "WARN")
        print_status("Installing missing packages...", "WAIT")
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-r',
                       str(PROJECT_ROOT / 'requirements.txt')],
                       capture_output=True)
        print_status("Packages installed", "OK")
    else:
        print_status("Python dependencies OK", "OK")

    return True


def setup_ollama():
    """Run Ollama setup."""
    from installer.setup_ollama import setup_ollama as run_setup
    return run_setup()


def load_env_config():
    """Load existing .env configuration."""
    config = {
        'DB_HOST': 'localhost',
        'DB_PORT': '3306',
        'DB_USER': 'makerspace',
        'DB_PASSWORD': 'makerspace2024',
        'DB_NAME': 'makerspace_rag',
    }

    if ENV_FILE.exists():
        with open(ENV_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    config[key.strip()] = value.strip()

    return config


def save_env_config(config):
    """Save configuration to .env file."""
    content = """# Makerspace RAG Configuration
# Generated by launcher

# Database
DB_HOST={DB_HOST}
DB_PORT={DB_PORT}
DB_USER={DB_USER}
DB_PASSWORD={DB_PASSWORD}
DB_NAME={DB_NAME}

# Flask
FLASK_ENV=production
FLASK_HOST=127.0.0.1
FLASK_PORT=5000

# Ollama
OLLAMA_HOST=http://127.0.0.1:11434
LLM_MODEL=llama3
EMBEDDING_MODEL=mxbai-embed-large

# Admin
ADMIN_USERNAME=admin
ADMIN_PASSWORD=makerspace2024
""".format(**config)

    with open(ENV_FILE, 'w') as f:
        f.write(content)

    print_status(f"Configuration saved to {ENV_FILE}", "OK")


def run_database_config_wizard():
    """Interactive database configuration wizard."""
    print("\n" + "-"*60)
    print("  DATABASE CONFIGURATION")
    print("-"*60)

    config = load_env_config()

    print("\n  Choose database location:\n")
    print("    [1] Local database (MariaDB on this machine)")
    print("    [2] Remote database (MariaDB on another machine)")
    print()

    choice = input("  Enter choice (1/2) [1]: ").strip() or "1"

    if choice == "2":
        print("\n  Enter remote database settings:\n")

        host = input(f"    Database host [{config['DB_HOST']}]: ").strip()
        if host:
            config['DB_HOST'] = host

        port = input(f"    Database port [{config['DB_PORT']}]: ").strip()
        if port:
            config['DB_PORT'] = port

        user = input(f"    Database user [{config['DB_USER']}]: ").strip()
        if user:
            config['DB_USER'] = user

        password = input(f"    Database password [{config['DB_PASSWORD']}]: ").strip()
        if password:
            config['DB_PASSWORD'] = password

        db_name = input(f"    Database name [{config['DB_NAME']}]: ").strip()
        if db_name:
            config['DB_NAME'] = db_name
    else:
        # Local database - use defaults
        config['DB_HOST'] = 'localhost'
        print_status("Using local database (localhost)", "OK")

    # Save configuration
    save_env_config(config)

    # Set environment variables for current session
    for key, value in config.items():
        os.environ[key] = value

    return config


def setup_local_database():
    """Setup local MariaDB database."""
    print_status("Setting up local database...", "WAIT")

    try:
        from installer.setup_database import (
            find_mariadb,
            check_mariadb_running,
            configure_remote_access,
            run_sql_script,
            SCRIPT_DIR as DB_SCRIPT_DIR
        )

        # Find MariaDB
        mariadb_dir = find_mariadb()
        if not mariadb_dir:
            print_status("MariaDB not found", "ERROR")
            print_status("Please install MariaDB from https://mariadb.org/download/", "INFO")
            return False

        print_status(f"Found MariaDB at: {mariadb_dir}", "OK")

        # Check if running
        if not check_mariadb_running():
            print_status("Starting MariaDB service...", "WAIT")
            subprocess.run(['net', 'start', 'MariaDB'], capture_output=True)
            time.sleep(2)

        if check_mariadb_running():
            print_status("MariaDB service running", "OK")
        else:
            print_status("Could not start MariaDB service", "ERROR")
            return False

        # Configure for remote access (also works for local)
        configure_remote_access(mariadb_dir)

        # Run SQL setup
        sql_file = SCRIPT_DIR / 'database_setup.sql'
        if sql_file.exists():
            print_status("Creating database and user...", "WAIT")
            # Try without password first (common for fresh installs)
            if not run_sql_script(mariadb_dir, sql_file, None):
                # If failed, try with common default passwords
                for pwd in ['', 'root', 'mysql']:
                    if run_sql_script(mariadb_dir, sql_file, pwd):
                        break

        print_status("Local database setup complete", "OK")
        return True

    except Exception as e:
        print_status(f"Database setup error: {e}", "ERROR")
        return False


def check_database():
    """Check database connection."""
    config = load_env_config()

    # Set environment variables
    for key, value in config.items():
        os.environ[key] = value

    try:
        os.chdir(PROJECT_ROOT)

        # Force reload of config module
        if 'app.config' in sys.modules:
            del sys.modules['app.config']
        if 'app' in sys.modules:
            del sys.modules['app']

        from app import create_app
        app = create_app()

        with app.app_context():
            from app.extensions import db
            db.session.execute(db.text('SELECT 1'))
            print_status("Database connection OK", "OK")
            return True
    except Exception as e:
        error_msg = str(e)
        if "Access denied" in error_msg:
            print_status("Database access denied - check credentials", "ERROR")
        elif "Can't connect" in error_msg or "Connection refused" in error_msg:
            print_status("Cannot connect to database server", "ERROR")
        else:
            print_status(f"Database error: {e}", "ERROR")
        return False


def import_components():
    """Import components from JSON to database."""
    print_status("Importing components to database...", "WAIT")

    try:
        from app import create_app
        from app.extensions import db
        from app.models.component import Component

        app = create_app()

        with app.app_context():
            # Check if data already exists
            existing_count = Component.query.count()
            if existing_count > 0:
                print_status(f"Database already has {existing_count} components - skipping import", "OK")
                return True

            # Read JSON file
            json_path = PROJECT_ROOT / 'knowledge' / 'components.json'
            if not json_path.exists():
                print_status("components.json not found - skipping import", "WARN")
                return True

            with open(json_path, 'r', encoding='utf-8') as f:
                data = json.load(f)

            # Import components
            imported = 0
            for kategori_key, kategori_data in data.items():
                kategori_navn = kategori_data.get('name_no', kategori_key)
                components = kategori_data.get('components', [])

                for comp in components:
                    name = comp.get('name', comp.get('id', 'Ukjent'))
                    location = comp.get('location', 'Ukjent')

                    db_comp = Component(
                        name=name,
                        hylleplass=location.upper() if location else 'UKJENT',
                        kategori=kategori_navn,
                        forbruksvare=comp.get('forbruksvare', False),
                        restock=comp.get('restock', False),
                        antall=comp.get('antall', 0)
                    )
                    db.session.add(db_comp)
                    imported += 1

            db.session.commit()
            print_status(f"Imported {imported} components", "OK")
            return True

    except Exception as e:
        print_status(f"Component import error: {e}", "ERROR")
        return False


def open_browser_delayed(url, delay=3):
    """Open browser after a delay."""
    time.sleep(delay)
    webbrowser.open(url)


def start_application():
    """Start the Flask application."""
    os.chdir(PROJECT_ROOT)

    # Reload config
    config = load_env_config()
    for key, value in config.items():
        os.environ[key] = value

    # Import and create app
    from app import create_app
    app = create_app()

    # Get configuration
    host = os.environ.get('FLASK_HOST', '127.0.0.1')
    port = int(os.environ.get('FLASK_PORT', 5000))
    url = f"http://localhost:{port}"

    print("\n" + "="*60)
    print_status(f"Starting Makerspace RAG at {url}", "OK")
    print("="*60)
    print("\n  Press Ctrl+C to stop the server\n")

    # Open browser in background thread
    browser_thread = threading.Thread(
        target=open_browser_delayed,
        args=(url, 2),
        daemon=True
    )
    browser_thread.start()

    # Start Flask (this blocks)
    app.run(host=host, port=port, debug=False, use_reloader=False)


def run_first_time_setup():
    """Run first-time setup wizard."""
    print("\n" + "="*60)
    print("  FIRST TIME SETUP")
    print("="*60)

    # Step 1: Ollama
    print("\n[1/4] Setting up Ollama...")
    if not setup_ollama():
        print_status("Ollama setup failed - you can install it manually later", "WARN")

    # Step 2: Database configuration
    print("\n[2/4] Database configuration...")
    config = run_database_config_wizard()

    # If local, setup the database
    if config.get('DB_HOST', 'localhost') == 'localhost':
        setup_local_database()

    # Step 3: Check database connection
    print("\n[3/4] Checking database connection...")
    db_ok = check_database()

    if not db_ok:
        print("\n  Database connection failed. Options:")
        print("    [1] Reconfigure database settings")
        print("    [2] Continue anyway (limited functionality)")
        print("    [3] Exit")

        choice = input("\n  Enter choice (1/2/3) [1]: ").strip() or "1"

        if choice == "1":
            config = run_database_config_wizard()
            if config.get('DB_HOST', 'localhost') == 'localhost':
                setup_local_database()
            db_ok = check_database()
        elif choice == "3":
            return False

    # Step 4: Import components
    if db_ok:
        print("\n[4/4] Importing component data...")
        import_components()

    # Mark as initialized
    mark_initialized()

    print("\n" + "="*60)
    print_status("First time setup complete!", "OK")
    print("="*60)

    return True


def main():
    """Main launcher function."""
    print_banner()

    first_run = is_first_run()

    if first_run:
        print("\n  This appears to be the first time running Makerspace RAG.")
        print("  Do you want to run the setup wizard?\n")
        print("    [1] Yes - Run first time setup (recommended)")
        print("    [2] No - Just start the application")
        print()

        choice = input("  Enter choice (1/2) [1]: ").strip() or "1"

        if choice == "1":
            if not run_first_time_setup():
                input("\nPress Enter to exit...")
                return 1
        else:
            print_status("Skipping setup wizard", "INFO")
            mark_initialized()
    else:
        print_status("Configuration found - starting application", "OK")

    # Quick checks before starting
    print("\n[Starting] Verifying setup...")

    # Check dependencies (silent if OK)
    check_python_dependencies()

    # Start application
    print("\n[Starting] Launching application...")
    try:
        start_application()
    except KeyboardInterrupt:
        print("\n")
        print_status("Application stopped", "OK")
    except Exception as e:
        print_status(f"Application error: {e}", "ERROR")
        input("\nPress Enter to exit...")
        return 1

    return 0


if __name__ == '__main__':
    sys.exit(main())
