"""
Makerspace RAG - Main Launcher
One-click launcher that sets up everything and starts the application
"""

import os
import sys
import time
import webbrowser
import threading
import subprocess
from pathlib import Path

# Add parent directory to path for imports
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

ENV_FILE = PROJECT_ROOT / '.env'


def print_banner():
    """Print application banner."""
    print("\n" + "="*60)
    print("""
    __  __       _
   |  \/  | __ _| | _____ _ __ ___ _ __   __ _  ___ ___
   | |\/| |/ _` | |/ / _ \ '__/ __| '_ \ / _` |/ __/ _ \\
   | |  | | (_| |   <  __/ |  \__ \ |_) | (_| | (_|  __/
   |_|  |_|\__,_|_|\_\___|_|  |___/ .__/ \__,_|\___\___|
                                  |_|    RAG Assistant
    """)
    print("="*60)


def print_status(message, status="INFO"):
    """Print formatted status message."""
    icons = {"INFO": "i", "OK": "+", "WARN": "!", "ERROR": "x", "WAIT": "~"}
    icon = icons.get(status, "*")
    print(f"  [{icon}] {message}")


def check_python_dependencies():
    """Check if required Python packages are installed."""
    required = ['flask', 'flask_cors', 'flask_login', 'sqlalchemy', 'sklearn', 'numpy', 'requests', 'pymysql']
    missing = []

    for package in required:
        try:
            __import__(package.replace('-', '_'))
        except ImportError:
            missing.append(package)

    if missing:
        print_status(f"Missing packages: {', '.join(missing)}", "WARN")
        print_status("Installing missing packages...", "WAIT")
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-r',
                       str(PROJECT_ROOT / 'requirements.txt')],
                       capture_output=True)
        print_status("Packages installed", "OK")
    else:
        print_status("Python dependencies OK", "OK")

    return True


def setup_ollama():
    """Run Ollama setup."""
    from installer.setup_ollama import setup_ollama as run_setup
    return run_setup()


def is_first_run():
    """Check if this is the first run (no .env file)."""
    return not ENV_FILE.exists()


def load_env_config():
    """Load existing .env configuration."""
    config = {
        'DB_HOST': 'localhost',
        'DB_PORT': '3306',
        'DB_USER': 'makerspace',
        'DB_PASSWORD': 'makerspace2024',
        'DB_NAME': 'makerspace_rag',
    }

    if ENV_FILE.exists():
        with open(ENV_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    config[key.strip()] = value.strip()

    return config


def save_env_config(config):
    """Save configuration to .env file."""
    content = """# Makerspace RAG Configuration
# Generated by launcher

# Database
DB_HOST={DB_HOST}
DB_PORT={DB_PORT}
DB_USER={DB_USER}
DB_PASSWORD={DB_PASSWORD}
DB_NAME={DB_NAME}

# Flask
FLASK_ENV=production
FLASK_HOST=127.0.0.1
FLASK_PORT=5000

# Ollama
OLLAMA_HOST=http://127.0.0.1:11434
LLM_MODEL=llama3
EMBEDDING_MODEL=mxbai-embed-large

# Admin
ADMIN_USERNAME=admin
ADMIN_PASSWORD=makerspace2024
""".format(**config)

    with open(ENV_FILE, 'w') as f:
        f.write(content)

    print_status(f"Configuration saved to {ENV_FILE}", "OK")


def run_database_config_wizard():
    """Interactive database configuration wizard."""
    print("\n" + "-"*60)
    print("  DATABASE CONFIGURATION")
    print("-"*60)

    config = load_env_config()

    print("\n  Choose database location:\n")
    print("    [1] Local database (MariaDB on this machine)")
    print("    [2] Remote database (MariaDB on another machine)")
    print()

    choice = input("  Enter choice (1/2) [1]: ").strip() or "1"

    if choice == "2":
        print("\n  Enter remote database settings:\n")

        host = input(f"    Database host [{config['DB_HOST']}]: ").strip()
        if host:
            config['DB_HOST'] = host

        port = input(f"    Database port [{config['DB_PORT']}]: ").strip()
        if port:
            config['DB_PORT'] = port

        user = input(f"    Database user [{config['DB_USER']}]: ").strip()
        if user:
            config['DB_USER'] = user

        password = input(f"    Database password [{config['DB_PASSWORD']}]: ").strip()
        if password:
            config['DB_PASSWORD'] = password

        db_name = input(f"    Database name [{config['DB_NAME']}]: ").strip()
        if db_name:
            config['DB_NAME'] = db_name
    else:
        # Local database - use defaults
        config['DB_HOST'] = 'localhost'
        print_status("Using local database (localhost)", "OK")

    # Save configuration
    save_env_config(config)

    # Set environment variables for current session
    for key, value in config.items():
        os.environ[key] = value

    return config


def setup_local_database():
    """Setup local MariaDB database."""
    print_status("Setting up local database...", "WAIT")

    try:
        from installer.setup_database import (
            find_mariadb,
            check_mariadb_running,
            configure_remote_access,
            run_sql_script,
            configure_firewall,
            restart_mariadb,
            SCRIPT_DIR as DB_SCRIPT_DIR
        )

        # Find MariaDB
        mariadb_dir = find_mariadb()
        if not mariadb_dir:
            print_status("MariaDB not found", "ERROR")
            print_status("Please install MariaDB from https://mariadb.org/download/", "INFO")
            return False

        print_status(f"Found MariaDB at: {mariadb_dir}", "OK")

        # Check if running
        if not check_mariadb_running():
            print_status("Starting MariaDB service...", "WAIT")
            subprocess.run(['net', 'start', 'MariaDB'], capture_output=True)
            time.sleep(2)

        if check_mariadb_running():
            print_status("MariaDB service running", "OK")
        else:
            print_status("Could not start MariaDB service", "ERROR")
            return False

        # Configure for remote access (also works for local)
        configure_remote_access(mariadb_dir)

        # Run SQL setup
        sql_file = SCRIPT_DIR / 'database_setup.sql'
        if sql_file.exists():
            print_status("Creating database and user...", "WAIT")
            # Try without password first (common for fresh installs)
            if not run_sql_script(mariadb_dir, sql_file, None):
                # If failed, try with common default passwords
                for pwd in ['', 'root', 'mysql']:
                    if run_sql_script(mariadb_dir, sql_file, pwd):
                        break

        print_status("Local database setup complete", "OK")
        return True

    except Exception as e:
        print_status(f"Database setup error: {e}", "ERROR")
        return False


def check_database():
    """Check database connection."""
    config = load_env_config()

    # Set environment variables
    for key, value in config.items():
        os.environ[key] = value

    try:
        os.chdir(PROJECT_ROOT)

        # Force reload of config module
        if 'app.config' in sys.modules:
            del sys.modules['app.config']
        if 'app' in sys.modules:
            del sys.modules['app']

        from app import create_app
        app = create_app()

        with app.app_context():
            from app.extensions import db
            db.session.execute(db.text('SELECT 1'))
            print_status("Database connection OK", "OK")
            return True
    except Exception as e:
        error_msg = str(e)
        if "Access denied" in error_msg:
            print_status("Database access denied - check credentials", "ERROR")
        elif "Can't connect" in error_msg or "Connection refused" in error_msg:
            print_status("Cannot connect to database server", "ERROR")
        else:
            print_status(f"Database error: {e}", "ERROR")
        return False


def open_browser_delayed(url, delay=3):
    """Open browser after a delay."""
    time.sleep(delay)
    webbrowser.open(url)


def start_application():
    """Start the Flask application."""
    os.chdir(PROJECT_ROOT)

    # Reload config
    config = load_env_config()
    for key, value in config.items():
        os.environ[key] = value

    # Import and create app
    from app import create_app
    app = create_app()

    # Get configuration
    host = os.environ.get('FLASK_HOST', '127.0.0.1')
    port = int(os.environ.get('FLASK_PORT', 5000))
    url = f"http://localhost:{port}"

    print("\n" + "="*60)
    print_status(f"Starting Makerspace RAG at {url}", "OK")
    print("="*60)
    print("\n  Press Ctrl+C to stop the server\n")

    # Open browser in background thread
    browser_thread = threading.Thread(
        target=open_browser_delayed,
        args=(url, 2),
        daemon=True
    )
    browser_thread.start()

    # Start Flask (this blocks)
    app.run(host=host, port=port, debug=False, use_reloader=False)


def main():
    """Main launcher function."""
    print_banner()

    first_run = is_first_run()

    # Step 1: Check Python dependencies
    print("\n[Step 1/5] Checking Python dependencies...")
    if not check_python_dependencies():
        print_status("Failed to install dependencies", "ERROR")
        input("\nPress Enter to exit...")
        return 1

    # Step 2: Setup Ollama
    print("\n[Step 2/5] Setting up Ollama...")
    if not setup_ollama():
        print_status("Ollama setup failed", "ERROR")
        print_status("You can try installing Ollama manually from https://ollama.com", "INFO")
        input("\nPress Enter to exit...")
        return 1

    # Step 3: Database configuration (first run or reconfigure)
    print("\n[Step 3/5] Database configuration...")
    if first_run:
        print_status("First run detected - running setup wizard", "INFO")
        config = run_database_config_wizard()

        # If local, setup the database
        if config.get('DB_HOST', 'localhost') == 'localhost':
            setup_local_database()
    else:
        print_status("Using existing configuration", "OK")

    # Step 4: Check database connection
    print("\n[Step 4/5] Checking database connection...")
    db_ok = check_database()

    if not db_ok:
        print("\n  Database connection failed. Options:")
        print("    [1] Reconfigure database settings")
        print("    [2] Continue anyway (limited functionality)")
        print("    [3] Exit")

        choice = input("\n  Enter choice (1/2/3) [1]: ").strip() or "1"

        if choice == "1":
            config = run_database_config_wizard()
            if config.get('DB_HOST', 'localhost') == 'localhost':
                setup_local_database()
            db_ok = check_database()
        elif choice == "3":
            return 1
        # choice == "2" continues anyway

    # Step 5: Start application
    print("\n[Step 5/5] Starting application...")
    try:
        start_application()
    except KeyboardInterrupt:
        print("\n")
        print_status("Application stopped", "OK")
    except Exception as e:
        print_status(f"Application error: {e}", "ERROR")
        input("\nPress Enter to exit...")
        return 1

    return 0


if __name__ == '__main__':
    sys.exit(main())
